[package]
name = "veda-queue2storage"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
env_logger = "0.6"
log = "0.4"
url = "2.1.1"
csv = "1.1"
scan_fmt = "0.1.3"

#v_common = { package = "v-common", path = "../../../v-common" }
v_common = { package = "v-common", version = "=0.17.5", features = ["tokio_0_2", "tt_2", "awc_2"] }
v-storage = "0.1"
v-individual-model = "0.2.5"
rmp = "=0.8.10"
