[package]
name = "veda-geo-indexer"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
redis = "0.12.0"
env_logger = "0.6"
log = "0.4"
rust-ini = "0.16"

v_queue = "0.1"

v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
