[package]
name = "v_az_lmdb"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[lib]
path = "src/az-lmdb.rs"

[dependencies]
lazy_static = "1.4"
lmdb-rs-m = "0.7.7"

v_authorization = "0.1.0"

