dist: trusty
sudo: required

language: node_js
node_js: "stable"

before_install:
  - stty cols 80
  - sudo apt-get install nodejs-legacy
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt --save-dev

addons:
#  firefox: latest
#  sauce_connect:
#    username: semanticmachines
#    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

# Build
install:
  - ./control-install.sh&>install.log 
  - source $HOME/.cargo/env
  - dub -v fetch vibe-d --version=0.7.30
#  - npm install --save-dev testcafe-browser-provider-saucelabs
  - npm install --save-dev testcafe
  - go version
  - dmd --version    
  - rustc -V          
  - ./build.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - fluxbox >/dev/null 2>&1 &
  - ./control-start.sh
  - sleep 180

script:
  - travis_wait 20 grunt test --stack --verbose
  - testcafe chromium qa/testcafe/testLogin.js
  - testcafe chromium qa/testcafe/testLanguage.js
  - testcafe chromium qa/testcafe/testAttributiveSearchPerson.js
  - testcafe chromium qa/testcafe/testComment.js
  - testcafe chromium qa/testcafe/testCreatingNetInterface.js
  - testcafe chromium qa/testcafe/testDeleteAndRecovery.js
  - testcafe chromium qa/testcafe/testJournal.js
  - testcafe chromium qa/testcafe/testPerson.js
  - testcafe chromium qa/testcafe/testRights.js
  - testcafe chromium qa/testcafe/testSearchRangeOfDates.js
  - testcafe chromium qa/testcafe/testVersionedDocument.js
  - testcafe chromium qa/testcafe/testSimpleNet.js
  - testcafe chromium qa/testcafe/testSimpleNet2.js  
  - testcafe chromium qa/testcafe/testSimpleNet3.js  

after_script:
  - ./control-stop.sh

after_failure:
  - ./control-stop.sh
  - ./send-to-chunk-io.sh