dist: trusty
sudo: required

language: node_js
node_js: "stable"

before_install:
  - stty cols 80
  - sudo apt-get install nodejs-legacy
  - sudo apt-get install curl
  - dub -v fetch vibe-d --version=0.7.30

addons:
#  firefox: latest
#  sauce_connect:
#    username: semanticmachines
#    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

# Build
install:
  - ./control-install.sh 
#&>install.log    
#  - npm install --save-dev testcafe-browser-provider-saucelabs
  - npm install --save-dev testcafe
  - go version
  - dmd --version    
  - rustc -V          
  - ./build.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 60
  - fluxbox >/dev/null 2>&1 &
  - ./control-start.sh

script:
  - travis_wait 20 grunt test --stack --verbose
  - testcafe chromium qa/testcafe

after_script:
  - ./control-stop.sh

after_failure:
  - ./control-stop.sh
  - ./send-to-chunk-io.sh