sudo: required
dist: trusty

addons:
  sauce_connect:
    username: semanticmachines
    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
    no_ssl_bump_domains: localhost

env:
  global:
    - secure: PYwCZBpLe87Qg2RXibiGk9LrNrkFMlGuFnf/mp+f5kc4bFoVMo7Pl+Rdl4S1H33kLYK6d3pFggddwWxO7HGH9IyHzQ6Gfu3u9gR9rJXovQYfEp8muDCJDXvLEUoMxRgnRPa202p+BUnrNMwebxYHmwgef0s1dYQpRsewmPWHevk=
    - secure: s1BV5JjhQIIdasowuMW2OqH5LjvN3tnU+sEGdz4HxWpHufgFUeNBVzu13S85qSxdch55lCyB4ft58PAX3q0wHFPYvBEwkvMlSFny7LeiytW9HZ/fkCG+Dwh6H6OEK1jKQriXZrYLQm4m6gnnAQYsUpDhxP12YejyyBbfaVW73Og=

# Load all dependencies
# Compile vibe-d before main project to prevent OutOfMemory issue
before_install:
  - ./control-install.sh&>install.log    
  - dub -v fetch vibe-d --version=0.7.30
  - npm install selenium-webdriver@2.47.0
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt --save-dev
  - npm install coveralls --save-dev
  - npm install grunt-coveralls --save-dev

# Build
install:
  - go version
  - ./build.sh
  - sudo timedatectl set-ntp no
  - sudo date --set "15:00:00"


# Run service as daemon and GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ./control-start.sh
  - sleep 180  # give Web server some time to bind to sockets, load startup data, etc
  - sudo date --set "15:01:00"
  - date

# Run API & integration test
script:
  - grunt test --stack --verbose
# - grunt coveralls
#  - node ./qa/testAPI.js
  - node ./qa/testLogin.js
#  - sudo date --set "15:02:00"
#  - node ./qa/testSendGet.js
  - node ./qa/testDeleteAndRecovery.js
  - node ./qa/testRights.js
#  - sudo date --set "15:04:00"
  - node ./qa/testComment.js
  - node ./qa/testVersionedDocument.js
  - sudo date --set "15:05:00"
  - node ./qa/testJournal.js
  - node ./qa/testAttachment.js
  - sudo date --set "15:06:00"
  - date
  - node ./qa/testPager.js
  - node ./qa/testSearchRangeOfDates.js
  - sudo date --set "15:07:00"
  - node ./qa/testAttributiveSearchPerson.js
  - node ./qa/testCreatingNetInterface.js
  - sudo date --set "15:08:00"
  - travis_wait 20 node ./qa/testInbox.js
  - travis_wait 20 node ./qa/testRepeatComplexRoute.js
  - sudo date --set "15:09:00"
  - travis_wait 20 node ./qa/testNetComplexRoute.js
  - travis_wait 20 node ./qa/testSimpleNet.js
  - sudo date --set "15:10:00"
  - travis_wait 20 node ./qa/testSimpleNet2.js
  - travis_wait 20 node ./qa/testSimpleNet3.js
  - sudo date --set "15:11:00"
  - travis_wait 20 node ./qa/testSimpleWorkflow.js
  - travis_wait 20 node ./qa/testDelegationDocument.js
  - sudo date --set "15:12:00"
  - date
  - node ./qa/testDelegationTask.js

# Stop deamon and show log
after_script:
  - ./control-stop.sh
  - ./send-to-chunk-io.sh
#  - grunt coveralls

after_failure:
  - ./control-stop.sh
  - ./send-to-chunk-io.sh
