[package]
name = "veda-webserver"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-webserver"
path = "src/lib.rs"

[dependencies]
actix = "0.8.3"
actix-rt = "0.2.5"
actix-web = "1.0.8"
actix-web-actors = "1.0.2"
actix-redis = "0.6.1"
futures = "0.1.23"
chrono = "0.4"
redis-async = "0.4.0"
redis = "0.11.0-beta.1"
serde = "1.0"
serde_derive = "1.0.71"
env_logger = "0.6"
scan_fmt = "0.1.3"
log = "0.4"
rust-ini = "0.16"
rusty_tarantool = "0.1.3"
url = "1.7"
serde_json = "1.0"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
