[package]
name = "veda-webserver"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-webserver"
path = "src/main.rs"

[dependencies]
actix = "0.8.3"
actix-rt = "0.2.2"
actix-web = "1.0.2"
actix-web-actors = "1.0.0"
actix-redis = { git="https://github.com/actix/actix-redis.git" }
futures = "0.1.23"
chrono = "0.4"
redis-async = "0.4.0"
redis = "0.11.0-beta.1"
serde = "1.0.71"
serde_derive = "1.0.71"
env_logger = "0.6"
scan_fmt = "0.1.3"
log = "0.4"
rust-ini = "0.13"
v_search = { path = "../v-search" }
