[package]
name = "veda-search-index"
version = "0.1.0"
authors = ["Roman Karpov <roman.karpov@gmail.com>"]
edition = "2018"

[dependencies]
mysql = "17.0.0"
log = "0.4"
chrono = "0.4.9"

v_queue = { path = "../v-queue" }
v_search = { path = "../v-search" }
v_onto = { path = "../v-onto" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
