[package]
name = "veda-search-index-pt"
version = "0.1.0"
authors = ["Roman Karpov <roman.karpov@gmail.com>"]
edition = "2018"

[dependencies]
clickhouse-rs = {git = "https://github.com/xbinxu/clickhouse-rs", rev = "6950ce586050d97cb423c9d49f142e54416cd46f", default-features = false, features = ["async_std"] }
futures = "0.3.5"
log = "0.4"
chrono = "0.4"
chrono-tz = "0.5"
url = "2.1.1"
serde = "1.0.104"
bincode = "1.2.1"

v_queue = "0.1"

v_search = { path = "../v-search" }
v_onto = { path = "../v-onto" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
