[package]
name = "veda-fanout-email"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
lettre = "0.9"
lettre_email = "0.9"

v_queue = "0.1"

v_search = { path = "../v-search" }
v_onto = { path = "../v-onto" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
