[package]
name = "veda-ontologist"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-ontologist"
path = "src/main.rs"

[dependencies]
env_logger = "0.6"
log = "0.4"

v_queue = "0.1"

v_onto = { path = "../v-onto" }
v_ft_xapian = { path = "../v-ft-xapian" }
v_search = { path = "../v-search" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
