[package]
name = "netdata-veda-plugin"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
rust-ini = "0.14"
v_queue = { path = "../v-queue" }
