[package]
name = "veda-ro-storage"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
nng = "1.0.0"

#v_common = { package = "v-common", path = "../../../v-common" }
v_common = { package = "v-common", version = "0.17.2", features = ["tokio_1", "awc_3"] }
v-storage = "0.1"
v-individual-model = "0.2"
